name: transfer_learning

epoch: 600

batch_size: 32
d_hidden: 1024
d_model: 512
d_k: 32
d_v: 32
n_heads: 16
n_layers: 1
dropout: 0.5


# this is max length in positional encoding
n_position: 1024
src_max_len: 1024
trg_max_len: 1024

cut_ratio: 1
debug: 0



seqlen: 700
output_dir: results
model_type: 2d
finger_corr: true
loss_type: cos
warmup: 2000
para_src: 1
para_corr: 0.3

dataset: video2imu


train_user: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,18,19,20,21]
train_ori: [1,2,3,4]

test_user: [1,3,5,6,7,9,11,12,13,14,15,16]
test_ori: [1,2,3,4]

#left hand [1,3,5,6,13,15]
#right hand [7,9,11,12,14,16]


lr_mul: 2.0

seed: 0

upper: 30
lower: 10


# finger_list: [1,2,4]
finger_list: [1,2,3,4,5]
dim_in: 30
dim_out: 7


use_tb: false
save_mode: best
cuda: true
label_smoothing: true
src_is_text: false


n_videos_train: 10000
n_videos_val: 1000
n_videos_test: 1000


beam_size: 3
min_fre: 0
embs_share_weight: false
proj_share_weight: false
scale_emb_or_prj: prj